#!/usr/bin/env bash #this makes the script portable
# set -n 
# set -x
# set -e 

# Author: Doctype Human

# Date: 22.03.21

# Purpose: Showcasing simple index arrays

# License: GNU GENERAL PUBLIC LICENSE. VERSION 3, 2007

clear

#This is going to be a basic informative script

#echo " Index Arrays are a set of values that can be stored into one variable"
#echo ""
#sleep 2
#echo " They are called as index arrays since each value in assigned an index value in the form of an integer"
#echo ""
#sleep 2
#echo " Please read the script to see further details or explanation"
#echo ""
#sleep 2
simple_array=(one two three four five) #Declaring a simple array

echo "We have assigned these values to the array: ${simple_array[@]}" 	#Print all the values of the array


echo "This is the first value of the array: ${simple_array}" 		# Printing the first value of the array

#echo "This is the last value of the array: ${simple_array[-1]}"	#Printing the last value of the array

echo "These are the values from index value 1: ${simple_array[@]:1}" #Print all values of the array from the first index value

echo "These are three values from index value 1: ${simple_array[@]:1:3}" #Print three values from the first index value

echo "These are all the index values of the arary: ${!simple_array[@]}" #Print all index values of the array

echo "This is the length of the array: ${#simple_array[@]}" #Print the length of the array

custom_index=([11]=1 [22]=2 [33]=3 [44]=4 [55]=5)	#Declaring an array with custom index values

echo " We have created a new array with custom index values"

echo " The values of this array are: ${custom_index[@]}" #Print all the values of the array

echo " The index values of this array are: ${!custom_index[@]}" #Print index values of the array 

declare -a another_custom					# Declaring an index array with declare -a 

another_custom=([123]=this [1231]=array [42323]=has [111]=been [90]=declared [88]=differently) 

echo " We have declared a new array with custom index values. The value of the array are: ${another_custom[@]}"

echo " The index values of this array are: ${!another_custom[@]}" 

